---
- name: Packages - Update - Needs update
  ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/packages/update/needs-update.yml"

- name: Packages - Update
  when: system_cache_needs_update
  become: true
  ansible.builtin.package:
    update_cache: true
  register: result
  until: result.failed == false
  retries: "{{ system_retries }}"
