---
- name: Packages - Update - Pacman
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - archlinux-keyring
    state: latest
  register: result
  until: result.failed == false
  retries: "{{ system_retries }}"
  notify: update marker
