---
- name: Packages - Update - Needs update
  ansible.builtin.import_tasks:
    file: "{{ role_path }}/tasks/packages/update/needs-update.yml"

- name: Packages - Update - Pacman
  when: system_cache_needs_update
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - archlinux-keyring
    state: latest
  register: result
  until: result.failed == false
  retries: "{{ system_retries }}"
