---
- name: Package - Update - Portage
  vars:
    backend: "{{ system_portage_webrsync | ternary('webrsync', 'sync') }}"
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/packages/update/portage/{{ backend }}.yml"
