---
- name: Package - DB update - Portage
  become: true
  ansible.builtin.command:
    cmd: emerge --sync
  register: result
  changed_when: not "You are already up to date" in result.stdout
  until: result.failed == false
  retries: "{{ system_retries }}"
  notify: update marker
