---
system_networks_interfaces:
  - name: eth0
    description: Public network
    bootproto: dhcp
  - name: eth1
    description: Private network
    bootproto: static
    ip: 192.168.250.3/24
    routes:
      - 192.168.250.0/24

system_storages_partitions:
  - device: /dev/vda
    flags:
      - lvm

system_storages_vg:
  - vg: datastore
    pvs: /dev/vda1
