---
- name: Pacman - Yay - Check for the binary
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: system_bin_yay

- name: Pacman - Yay - Install
  when: not system_bin_yay.stat.exists
  block:
    - name: Pacman - Yay - Install build dependencies
      become: true
      community.general.pacman:
        name:
          - base-devel
          - fakeroot
          - git
          - go
          - make

    - name: Pacman - Yay - Temporary user for building sources securely
      when: ansible_user_id == 'root'
      ansible.builtin.user:
        name: build_user
        group: users

    - name: Pacman - Yay - Build from sources
      become: "{{ ansible_user_id == 'root' }}"
      become_user: build_user
      block:
        - name: Pacman - Yay - Clone from github
          ansible.builtin.git:
            repo: https://aur.archlinux.org/yay.git
            dest: /tmp/yay
            version: "{{ system_yay_version | default(omit) }}"

        - name: Pacman - Yay - Build
          ansible.builtin.command:
            cmd: makepkg --noconfirm -si
            chdir: /tmp/yay
            creates: /usr/bin/yay

    - name: Pacman - Yay - Remove the temporary user
      when: ansible_user_id == 'root'
      ansible.builtin.user:
        name: build_user
        state: absent
        remove: true

- name: Pacman - Yay - Ansible module
  become: true
  run_once: true
  delegate_to: localhost
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/mnussbaum/ansible-yay/master/yay
    dest: /usr/share/ansible/yay
    mode: "0755"
