---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  provision: true
platforms:
  - name: archlinux
    box: archlinux/archlinux
    provider_raw_config_args: &raw_config
      - "cpu_mode = 'host-passthrough'"
      - "disk_bus = 'virtio'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"
    instance_raw_config_args:
      - 'vm.provision :shell, inline: "pacman -Syu --noconfirm git net-tools python3 sudo unzip which"'
  - name: debian11
    box: debian/bullseye64
    provider_raw_config_args: *raw_config
  - name: el8
    box: generic/centos8s
    memory: 2048
    provider_raw_config_args: *raw_config
  # - name: el9
  #   box: generic/centos9s
  #   memory: 2048
  #   provider_raw_config_args: *raw_config
  - name: ubuntu1804
    box: generic/ubuntu1804
    provider_raw_config_args: *raw_config
  - name: ubuntu2004
    box: generic/ubuntu2004
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: ubuntu2204
    box: generic/ubuntu2204
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: ubuntu2210
    box: generic/ubuntu2210
    memory: 2048
    provider_raw_config_args: *raw_config
lint: ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
