---
- name: Converge customization
  hosts: all
  tasks:
    - name: Include gwerlas.system
      ansible.builtin.include_role:
        name: gwerlas.system
      vars:
        system_pkg_update: true
        system_hosts_domain: mydomain.tld
        system_hosts_localhost_aliases:
          - me
          - myself
        system_hosts_custom:
          - ip: '10.0.0.7'
            names:
              - host7
              - host7.domain.tld
        system_zsh_install: true
