---
- name: Converge customization
  hosts: all
  tasks:
    - name: Include gwerlas.system
      ansible.builtin.include_role:
        name: gwerlas.system
      vars:
        system_hosts_domain: mydomain.tld
        system_hosts_localhost_aliases:
          - me
          - myself
        system_hosts_custom:
          - ip: '10.0.0.7'
            names:
              - host7
              - host7.domain.tld
        system_users:
          - name: jane
            comment: System administrator
            group: "{{ 'adm' if ansible_os_family == 'Debian' else 'wheel' }}"
            groups:
              - users
            shell: /bin/zsh
          - name: john
            group: users
        system_users_groups:
          - name: my_company
        system_packages_update: true
        system_portage_directory: /data/gentoo
