---
- name: Verify role with the server profile (default)
  hosts: all
  tasks:

    - name: Check host FQDN
      ansible.builtin.assert:
        quiet: true
        that:
          - ansible_fqdn == inventory_hostname + '.mydomain.tld'

    - name: Command line tools
      ansible.builtin.command: "{{ item }} --version"
      changed_when: false
      with_items:
        - rsync
        - wget
        - zsh

    - name: Check sudo rules
      ansible.builtin.command: sudo -l
      register: result
      changed_when: false
      failed_when: item not in result.stdout
      loop:
        - "!visiblepw"
        - always_set_home
        - QTDIR
        - NOPASSWD

    - name: Check groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - administrators
        - gods
        - my_company
        - my_team

    - name: Check users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - jane
        - john

    - name: Check jane's group
      ansible.builtin.command:
        cmd: id -g -n jane
      register: result
      changed_when: false
      failed_when: result.stdout != 'administrators'

    - name: Check jane's SSH key
      become: true
      ansible.posix.authorized_key:
        key: ssh-rsa AAAA test
        user: jane
        state: present
      register: result
      failed_when: result is changed

    - name: ZSH configuration that should exists
      become: true
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /etc/skel/.zshrc
        - /etc/skel/.zsh/history
        - /home/jane/.zshrc
        - /home/jane/.zsh/history
        - /home/john/.zshrc
        - /home/john/.zsh/history
      register: result
      failed_when: not result.stat.exists

    - name: ZSH configuration that should not exists
      become: true
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /etc/skel/.zsh/prompt
        - /etc/skel/.zsh/prompt_git
        - /home/jane/.zsh/prompt
        - /home/jane/.zsh/prompt_git
        - /home/john/.zsh/prompt
        - /home/john/.zsh/prompt_git
      register: result
      failed_when: result.stat.exists
