---
- name: Verify role with the server profile (default)
  hosts: all
  tasks:

    - name: Check host FQDN
      ansible.builtin.assert:
        quiet: true
        that:
          - ansible_fqdn == inventory_hostname + '.mydomain.tld'

    - name: Command line tools
      ansible.builtin.command: "{{ item }} --version"
      changed_when: false
      with_items:
        - rsync
        - zsh

    - name: NTP Status
      when: ansible_service_mgr == 'systemd'
      block:
        - name: Systemd
          ansible.builtin.command:
            cmd: timedatectl show -p NTPSynchronized --value
          register: result
          failed_when: result.stdout != 'yes'
          changed_when: false
        - name: NTP Server
          ansible.builtin.command:
            cmd: timedatectl show-timesync --property ServerName --value
          register: result
          failed_when: result.stdout not match('\d.fr.pool.ntp.org')
          changed_when: false

    - name: Check sudo rules
      ansible.builtin.command: sudo -l
      register: result
      changed_when: false
      failed_when: item not in result.stdout
      loop:
        - "!visiblepw"
        - always_set_home
        - QTDIR
        - NOPASSWD

    - name: Check groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - administrators
        - gods
        - my_company
        - my_team

    - name: Check users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - jane
        - john

    - name: Check jane's group
      ansible.builtin.command:
        cmd: id -g -n jane
      register: result
      changed_when: false
      failed_when: result.stdout != 'administrators'
