molecule:
  image: gwerlas/molecule
  services:
    - docker:20.10-dind
  script: molecule test -s docker
  timeout: 2h
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
      - defaults/*
      - files/**/*
      - handlers/*
      - meta/*
      - molecule/**/*
      - tasks/**/*
      - templates/**/*
      - vars/**/*

import:
  stage: deploy
  image: gwerlas/ansible
  script: ansible-galaxy role import --token $GALAXY_TOKEN Gwerlas system
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_TAG'
