molecule:
  image: gwerlas/molecule
  services:
    - docker:20.10-dind
  script: molecule test

import:
  stage: deploy
  image: gwerlas/ansible
  script: ansible-galaxy role import --token $GALAXY_TOKEN Gwerlas system
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
