---
- name: Package - Update - Portage
  block:
    - name: Package - Update - Portage - Sync
      become: true
      ansible.builtin.command:
        cmd: emerge --sync
      register: result
      changed_when: not "You are already up to date" in result.stdout
      until: result.failed == false
      retries: "{{ system_retries }}"
      notify: update marker
  rescue:
    - name: Package - Update - Portage - Web rsync
      ansible.builtin.import_tasks: "{{ role_path }}/tasks/packages/update/portage/webrsync.yml"
