---
- name: CA - Load variables
  when: system_packages is undefined
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

- name: CA - Certificates
  tags:
    - ca
  become: true
  ansible.builtin.copy:
    src: "{{ certificate }}"
    dest: "{{ ca_certificates.path }}"
    mode: "0644"
  loop: "{{ system_ca_certificates }}"
  loop_control:
    loop_var: certificate
  notify: update ca
