---
- name: CA - Load variables
  when: default_ca is undefined
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/vars.yml"

- name: CA certificates
  tags:
    - ca
  become: true
  ansible.builtin.copy:
    src: "{{ system_ca_certificate }}"
    dest: "{{ default_ca.path }}"
    mode: "0644"
  loop: "{{ system_ca_certificates }}"
  loop_control:
    loop_var: system_ca_certificate
  notify: update ca
