---
- name: Local host name
  become: true
  ansible.builtin.hostname:
    name: "{{ system_hostname }}"
  notify: Restart logind

- name: Display system hosts for debugging
  ansible.builtin.debug:
    var: system_hosts
    verbosity: 1

- name: Hosts names in /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ '{:<15}'.format(item.ip) }} {{ item.names | join(' ') }}"
    regexp: "^{{ item.ip }}"
  with_items: "{{ system_hosts }}"
  notify: Restart logind
