---
- name: Local host name
  become: true
  ansible.builtin.hostname:
    name: "{{ system_hostname }}"
  notify: restart logind

- name: Display system hosts for debugging
  ansible.builtin.debug:
    var: system_hosts
    verbosity: 1

- name: Hosts names in /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ '{:<15}'.format(item.ip) }} {{ item.names | join(' ') }}"
    regexp: "^{{ item.ip }}"
  with_items: "{{ system_hosts }}"
  notify: restart logind

- name: OpenRC host and domain name configuration
  when: ansible_service_mgr == "openrc"
  become: true
  notify: restart hostname
  block:
    - name: Remove /etc/hostname
      ansible.builtin.file:
        path: /etc/hostname
        state: absent

    - name: Domain name
      ansible.builtin.lineinfile:
        path: /etc/conf.d/net
        line: 'dns_domain_lo="{{ system_domainname }}"'
        regex: ^dns_domain_lo=
        create: true
        group: wheel
        mode: 0664
