---
- name: Hosts - Local hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ system_hostname }}"
  notify: restart hostname

- name: Hosts - OpenRC configuration
  when: ansible_service_mgr == "openrc"
  become: true
  notify: restart hostname
  block:
    - name: Hosts - OpenRC - Remove /etc/hostname
      ansible.builtin.file:
        path: /etc/hostname
        state: absent

    - name: Hosts - OpenRC - Domain name
      when: system_domain is defined
      ansible.builtin.lineinfile:
        path: /etc/conf.d/net
        line: 'dns_domain_lo="{{ system_domain }}"'
        regex: ^dns_domain_lo=
        create: true
        group: wheel
        mode: 0664

- name: /etc/hosts
  when: system_hosts | length > 0
  block:
    - name: Hosts - Display hosts for debugging
      ansible.builtin.debug:
        var: etc_hosts
        verbosity: 1

    - name: Hosts - Names in /etc/hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ '{:<15}'.format(host.ip) }} {{ host.names | join(' ') }}"
        regexp: "^{{ host.ip | regex_escape }}"
      loop: "{{ etc_hosts }}"
      loop_control:
        loop_var: host
      notify: restart hostname
