---
- name: Hosts names resolution
  when: system_manage_hosts_names
  ansible.builtin.import_tasks: hosts-names.yml

- name: System packages
  ansible.builtin.import_tasks: packages.yml

- name: Configure ZSH
  when: system_install_zsh
  ansible.builtin.import_tasks: zsh.yml

- name: Firewall
  when: system_firewall_managed
  ansible.builtin.import_tasks: firewall.yml
