---
- name: Load variables
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

- name: Proxies
  when: system_manage_proxies
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/proxies.yml"

- name: Hosts
  when: system_manage_hosts
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/hosts.yml"

- name: Packages
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/packages.yml"

- name: Network management
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/networks.yml"

- name: Storages
  when: system_manage_storages
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/storages.yml"

- name: Sudo
  when: system_manage_sudo
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/sudo.yml"

- name: Users
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/users.yml"

- name: CA certificates
  when: system_ca_certificates | length > 0
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/ca.yml"

- name: Time
  when: system_manage_time
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/time.yml"

- name: Firewall
  when: system_manage_firewall
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/firewall.yml"
