---
- name: Sudo
  when: system_manage_sudo
  ansible.builtin.import_tasks: sudo.yml

- name: Hosts
  when: system_manage_hosts
  ansible.builtin.import_tasks: hosts.yml

- name: Proxies
  when: system_manage_proxies
  ansible.builtin.import_tasks: proxies.yml

- name: Packages
  ansible.builtin.import_tasks: packages.yml

- name: Time
  when: system_manage_time
  ansible.builtin.import_tasks: time.yml

- name: Users
  ansible.builtin.import_tasks: users.yml

- name: Firewall
  when: system_manage_firewall
  ansible.builtin.import_tasks: firewall.yml
