---
- name: Hosts
  when: system_manage_hosts
  ansible.builtin.import_tasks: hosts.yml

- name: Proxies
  ansible.builtin.import_tasks: proxies.yml

- name: Packages
  ansible.builtin.import_tasks: packages.yml

- name: Users
  ansible.builtin.import_tasks: users.yml

- name: Firewall
  when: system_manage_firewall
  ansible.builtin.import_tasks: firewall.yml
