---
- name: Hosts
  when: system_manage_hosts
  ansible.builtin.import_tasks: hosts.yml

- name: Proxy
  ansible.builtin.import_tasks: proxy.yml

- name: Packages
  ansible.builtin.import_tasks: packages.yml

- name: ZSH
  when: system_zsh_install
  ansible.builtin.import_tasks: zsh.yml

- name: Firewall
  when: system_manage_firewall
  ansible.builtin.import_tasks: firewall.yml
