---
- name: Networks - Load variables
  when: default_networks is undefined
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

- name: Networks - Prune unmanaged interfaces
  when: system_networks_interfaces_prune
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/networks/prune.yml"

- name: Networks - Distribution rules
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}-like.yml"
        - empty.yml
      paths:
        - "{{ role_path }}/tasks/networks"

- name: Networks - Interfaces configuration from template
  when: default_networks.template is defined
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/networks/from-template.yml"
