---
- name: Packages - Load variables
  when: system_packages is not defined
  ansible.builtin.import_tasks: vars.yml

- name: Packages - Package manager preparation
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_pkg_mgr }}-pre.yml"
        - empty.yml
      paths:
        - package-managers

- name: Packages - Update
  ansible.builtin.import_tasks: packages/update.yml

- name: Packages - Package managers post update
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_pkg_mgr }}-post.yml"
        - empty.yml
      paths:
        - package-managers

- name: Packages - Persist computed list as fact
  ansible.builtin.set_fact:
    cacheable: true
    system_packages_computed: "{{ system_packages_computed }}"

- name: Packages - Debug
  ansible.builtin.debug:
    var: system_packages_computed
    verbosity: 1

- name: Packages - Base system tools
  become: true
  ansible.builtin.package:
    name: "{{ system_packages_computed }}"
  register: result
  until: result.failed == false
  retries: "{{ system_retries }}"

- name: Packages - Upgrade
  when:
    - system_packages_upgrade
    - system_packages_upgrade_policy is defined
  become: true
  ansible.builtin.package:
    name: "{{ system_packages_upgrade_policy.name | default(omit) }}"
    state: "{{ system_packages_upgrade_policy.state | default(omit) }}"
    upgrade: "{{ system_packages_upgrade_policy.upgrade | default(omit) }}"
  register: result
  until: result.failed == false
  retries: "{{ system_retries }}"

- name: Packages - Reboot if needed
  ansible.builtin.import_tasks: reboot.yml
