---
- name: Packages - OS family settings
  ansible.builtin.include_vars: "packages/{{ ansible_os_family | lower }}-like.yml"

- name: Packages - Package manager preparation
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_pkg_mgr }}-pre.yml"
        - empty.yml
      paths:
        - package-managers

- name: Packages - Cache update detection script
  become: true
  ansible.builtin.template:
    src: needs-update.j2
    dest: "{{ system_bin_path }}/needs-update"
    mode: 0755

- name: Packages - Cache update detection
  ansible.builtin.command:
    cmd: needs-update
  changed_when: false
  register: system_packages_cache_needs_update
  failed_when: system_packages_cache_needs_update.rc > 1

- name: Packages - Cache update
  when: system_packages_cache_needs_update.rc == 1
  become: true
  ansible.builtin.package:
    sync: "{{ (ansible_pkg_mgr == 'portage') | ternary(true, omit) }}"
    update_cache: "{{ (ansible_pkg_mgr != 'portage') | ternary(true, omit) }}"
  register: result
  until: result.failed == false
  retries: 5
  notify: mark update

- name: Packages - Base system tools
  when: system_packages is defined
  become: true
  ansible.builtin.package:
    name: "{{ system_packages.common + (system_packages[system_profile] | default([])) }}"
  register: result
  until: result.failed == false
  retries: 5

- name: Packages - Update
  when:
    - system_packages_upgrade
    - system_packages_upgrade_policy is defined
  become: true
  ansible.builtin.package:
    name: "{{ system_packages_upgrade_policy.name | default(omit) }}"
    state: "{{ system_packages_upgrade_policy.state | default(omit) }}"
    upgrade: "{{ system_packages_upgrade_policy.upgrade | default(omit) }}"
  register: result
  until: result.failed == false
  retries: 5

- name: Packages - Package managers post operations
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_pkg_mgr }}-post.yml"
        - empty.yml
      paths:
        - package-managers

- name: Packages - Reboot if needed
  ansible.builtin.import_tasks: reboot.yml
