---
- name: Packages - Load variables
  when: system_packages_computed is undefined
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

- name: Packages
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/packages/{{ pkg_task }}.yml"
  loop:
    - prepare
    - update
    - requirements
    - prewash
    - upgrade
    - install
    - cleanup
  loop_control:
    loop_var: pkg_task

- name: Packages - Reboot if needed
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/reboot.yml"
