---
- name: Reboot - Load variables
  when: reboot_detection_policy is undefined
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/vars.yml"

- name: Reboot
  when:
    - "'container' not in ansible_virtualization_tech_guest"
    - reboot_detection_policy is defined
  block:
    - name: Reboot - Package providing the command that determine if a restart is needed
      when: reboot_detection_policy.package is defined
      become: true
      ansible.builtin.package:
        name: "{{ reboot_detection_policy.package }}"

    - name: Reboot - Determination script
      when:
        - reboot_detection_policy.use_template is defined
        - reboot_detection_policy.use_template
      become: true
      ansible.builtin.template:
        src: needs-restarting.j2
        dest: "{{ system_bin_path }}/needs-restarting"
        mode: "0755"

    - name: Reboot - Check if it's needed
      ansible.builtin.command:
        cmd: "{{ reboot_detection_policy.cmd | default('needs-restarting -r') }}"
      register: result
      changed_when: result.rc == 1
      failed_when: result.rc > 1
      notify: reboot
