---
- name: Time - Load variables
  when: system_packages_computed is undefined
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

- name: Time - Zone
  when: system_time_zone is defined
  become: true
  community.general.timezone:
    name: "{{ system_time_zone }}"

- name: Checks
  when: time_backend_name not in time_backends
  block:
    - name: Debug
      ansible.builtin.debug:
        var: time_backends

    - name: Check the backend
      ansible.builtin.fail:
        msg: "{{ time_backend_name }} not supported"

- name: Wanted backend
  become: true
  block:
    - name: Time - Configuration file
      when: system_time_servers | length > 0
      ansible.builtin.template:
        src: "{{ templates[time_backend_name] }}.j2"
        dest: "/etc/{{ templates[time_backend_name] }}"
        mode: "0644"
      notify: restart time service

    - name: Time - Service
      ansible.builtin.service:
        name: "{{ services[time_backend_name] }}"
        state: started
        enabled: true
