---
- name: Zsh - Skeleton directory
  become: true
  ansible.builtin.file:
    path: "/etc/skel/.zsh"
    state: directory
    mode: 0700

- name: Zsh - Skeleton files
  become: true
  ansible.builtin.copy:
    dest: "/etc/skel/{{ system_zsh_skel_file }}"
    src: "{{ system_zsh_skel_file }}"
    mode: 0600
  loop:
    - .zshrc
    - .zsh/history
    - .zsh/prompt
    - .zsh/prompt_git
  loop_control:
    loop_var: system_zsh_skel_file
