---
- name: ZSH distribution package
  become: true
  ansible.builtin.package:
    name: zsh

- name: ZSH user configuration
  block:
    - name: ZSH sub directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.zsh"
        state: directory
        mode: 0700
    - name: ZSH configuration files
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/{{ _zsh_config_file }}"
        src: "{{ _zsh_config_file }}"
        mode: 0600
      loop:
        - .zshrc
        - .zsh/history
        - .zsh/prompt
        - .zsh/prompt_git
      loop_control:
        loop_var: _zsh_config_file
