---
- name: ZSH - Distribution package
  become: true
  ansible.builtin.package:
    name: zsh

- name: ZSH - User configuration
  block:
    - name: ZSH - User configuration - Directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.zsh"
        state: directory
        mode: 0700
    - name: ZSH - User configuration - Files
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/{{ system_zsh_config_file }}"
        src: "{{ system_zsh_config_file }}"
        mode: 0600
      loop:
        - .zshrc
        - .zsh/history
        - .zsh/prompt
        - .zsh/prompt_git
      loop_control:
        loop_var: system_zsh_config_file
