---
- name: Update RPM cache
  block:
    - name: Check for RPM cache
      ansible.builtin.find:
        recurse: true
        path: "/var/cache/{{ ansible_pkg_mgr }}"
        pattern: "(ansible_pkg_mgr == 'yum') | ternary('primary_db.sqlite', 'packages.db')"
        age: "{{ system_pkg_cache_max_age }}"
      register: _system_rpm_cache

    - name: Display result for debug
      ansible.builtin.debug:
        var: _system_rpm_cache
        verbosity: 1

    - name: Install Yum utils
      become: true
      ansible.builtin.yum:
        update_cache: "{{ _system_rpm_cache.matched == 0 }}"
        name: 'yum-utils'

- name: System update
  when: system_update
  block:
    - name: Upgrade all packages
      become: true
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Check to see if we need a reboot
      ansible.builtin.command: needs-restarting -r
      register: _system_needs_restarting
      changed_when: "'Reboot is required' in _system_needs_restarting.stdout"
      failed_when: _system_needs_restarting.rc > 1

    - name: Display result for debug
      ansible.builtin.debug:
        var: _system_needs_restarting.rc
        verbosity: 1

    - name: Reboot
      become: true
      when: _system_needs_restarting.changed
      ansible.builtin.reboot:
        msg: "{{ system_update_reboot_msg }}"
