---
- name: Become root
  become: true
  block:
    - name: YUM - EPEL
      when: system_el_epel
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: YUM - Install
      ansible.builtin.yum:
        name: "{{ system_packages }}"
      register: result
      until: result.failed == false
      retries: "{{ system_retries }}"
