---
- name: Converge customization
  hosts: all
  tasks:
    - name: Include gwerlas.system
      ansible.builtin.include_role:
        name: gwerlas.system
      vars:
        system_profile: desktop/gnome
        system_http_proxy: http://192.168.122.1:3128
        system_https_proxy: "{{ system_http_proxy }}"
        system_ftp_proxy: "{{ system_http_proxy }}"
        system_users:
          - name: vagrant   # Console login: vagrant / vagrant
            password: "$6$sc1Fu113nXXNx/KT$ZZ9QpiisBuXevhxIUdlN6tbAyxsR3BYUBayVP2NH0DPF6//sKe2bQ6vDGM0/wfAxRYZAd0tMQYVUtoEq.reB41"
