---
- name: Verify role for Stream distributions
  hosts: all
  tasks:
    - name: Command line tools
      ansible.builtin.command: "{{ item }} --version"
      changed_when: false
      with_items:
        - lsusb

    - name: GDM service
      check_mode: true
      ansible.builtin.service:
        name: gdm
        state: started
      register: result
      failed_when: result.changed
