---
- name: Verify role for Stream distributions
  hosts: all
  tasks:
    - name: Rsync
      ansible.posix.synchronize:
        src: verify.yml
        dest: /tmp/verify.yml

    - name: Time synchronisation
      ansible.builtin.command:
        cmd: timedatectl
      register: result
      failed_when: |
        (result.rc > 0) or
        ('synchronized: yes' not in result.stdout) or
        ('service: active' not in result.stdout)
      changed_when: false

    - name: Command line tools
      ansible.builtin.command: "{{ item }} --version"
      changed_when: false
      with_items:
        - lsusb
