---
- name: Portage - System binaries
  when: "not in_container"
  block:
    - name: Portage - Kernel related packages settings
      ansible.builtin.copy:
        src: "{{ file }}"
        dest: "/etc/portage/{{ file }}"
        owner: "{{ ansible_user_id }}"
        group: portage
        mode: "0664"
      loop:
        - package.license/kernel
        - package.use/kernel
      loop_control:
        loop_var: file
      notify: emerge --newuse

    - name: Portage - Kernel package and its dependencies
      become: true
      community.general.portage:
        update: "{{ system_packages_upgrade }}"
        package:
          - sys-kernel/linux-firmware
          - virtual/dist-kernel
      register: system_emerge_kernel
      notify:
        - grub-mkconfig

    - name: Portage - Kernels
      ansible.builtin.find:
        path: /boot
        pattern: vmlinuz-*
      register: system_available_kernels

    - name: Portage - Kernel symlink for external modules
      become: true
      when: system_available_kernels.matched > 0
      ansible.builtin.file:
        src: /usr/src/linux-{{ (system_available_kernels.files | map(attribute='path') | map('regex_search', 'vmlinuz-(.*)', '\1') | last).0 }}
        dest: /usr/src/linux
        state: link
        force: true
      notify:
        - emerge @module-rebuild
