---
- name: Packages - Requirements - Portage - Use flags - Get installed Python versions
  ansible.builtin.command:
    cmd: equery -q list -F '$slot' dev-lang/python
  changed_when: false
  register: equery

- name: Packages - Requirements - Portage - Use flags - app-portage/cpuid2cpuflags package
  become: true
  community.general.portage:
    package:
      - app-portage/cpuid2cpuflags
    state: present

- name: Packages - Requirements - Portage - Use flags - CPU Flags
  ansible.builtin.command:
    cmd: cpuid2cpuflags
  register: cpuid2cpuflags
  changed_when: false

- name: Packages - Requirements - Portage - Use flags - Global use flags
  become: true
  vars:
    cpu_flags_key: "{{ cpuid2cpuflags.stdout | split(': ') | first }}"
    cpu_flag_values: "{{ cpuid2cpuflags.stdout | split(': ') | last }}"
    python_targets: |
      {{
        system_portage_python_targets |
        default(
          ['python'] |
          product(equery.stdout_lines | map('replace', '.', '_')) |
          map('join') |
          join(' ')
        )
      }}
  ansible.builtin.template:
    src: portage/make.conf.j2
    dest: /etc/portage/make.conf
    owner: root
    group: portage
    mode: "0664"
  notify: emerge --newuse
