---
- name: Packages - Prepare - Portage - Cache - Load initial config
  register: initial_config
  ansible.builtin.slurp:
    src: /etc/portage/make.conf

- name: Packages - Prepare - Portage - Cache - Configuration parameter
  vars:
    is_default: "{{ system_portage_directory == default_portage_directory }}"
    line: PORTDIR="{{ system_portage_directory }}"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/portage/make.conf
    line: "{{ line }}"
    regex: ^PORTDIR=
    state: "{{ is_default | ternary('absent', 'present') }}"

- name: Packages - Prepare - Portage - Cache - Predefined Portage directory
  ansible.builtin.set_fact:
    portdir_matches: "{{ initial_config.content | b64decode | regex_findall('(?<!#)PORTDIR=\"(.+)\"') }}"

- name: Packages - Prepare - Portage - Cache
  vars:
    initial_value: "{{ (portdir_matches | length > 0) | ternary(portdir_matches | last, default_portage_directory) }}"
  when: initial_value != system_portage_directory
  become: true
  block:
    - name: Packages - Prepare - Portage - Cache - DB directory
      ansible.builtin.file:
        path: "{{ system_portage_directory | dirname }}"
        state: directory
        mode: "0755"
        recurse: true

    - name: Packages - Prepare - Portage - Cache - Move data
      ansible.builtin.command:
        cmd: "mv '{{ initial_value }}' '{{ system_portage_directory }}'"
      changed_when: true
