---
- name: Packages - Prepare - Portage - Config
  ansible.builtin.template:
    src: portage/{{ file }}.j2
    dest: /etc/portage/{{ file }}
    owner: "{{ ansible_user_id }}"
    group: portage
    mode: "0664"
  loop:
    - binrepos.conf
    - package.license/kernels
    - package.use/{{ system_portage_kernel }}
    - package.use/firewalld
    - package.use/lvm2
    - package.use/libreoffice
  loop_control:
    loop_var: file
  notify: emerge --newuse
