---
- name: Packages - Prepare - Portage - Config
  ansible.builtin.copy:
    src: "{{ file }}"
    dest: "/etc/portage/{{ file }}"
    owner: "{{ ansible_user_id }}"
    group: portage
    mode: "0664"
  loop:
    - package.license/kernels
    - package.use/{{ system_portage_kernel }}
    - "{{ system_manage_firewall | ternary('package.use/firewalld', omit) }}"
  loop_control:
    loop_var: file
  notify: emerge --newuse
