---
- name: Packages - Prepare - Portage - Config - Directories
  become: true
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    group: portage
    mode: "0775"
  loop:
    - /etc/portage
    - /etc/portage/package.accept_keywords
    - /etc/portage/package.license
    - /etc/portage/package.mask
    - /etc/portage/package.use
    - /etc/portage/repos.conf
    - /etc/portage/savedconfig
  loop_control:
    loop_var: directory

- name: Packages - Prepare - Portage - Config - Files
  become: true
  ansible.builtin.template:
    src: portage/{{ file }}.j2
    dest: /etc/portage/{{ file }}
    group: portage
    mode: "0664"
  loop:
    - binrepos.conf
    - package.license/kernels
    - package.use/{{ system_portage_kernel }}
    - package.use/firewalld
    - package.use/lvm2
    - package.use/libreoffice
  loop_control:
    loop_var: file
  notify: emerge --newuse
