---
- name: Prepare - Portage - Deployer admin in portage group
  when: ansible_user_id != 'root'
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
      - portage

- name: Prepare - Portage - Reset SSH connection
  ansible.builtin.meta: reset_connection

- name: Prepare - Portage - Configuration directories
  become: true
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    group: portage
    mode: "0775"
  loop:
    - /etc/portage/
    - /etc/portage/package.license
    - /etc/portage/package.use
  loop_control:
    loop_var: dir

- name: Prepare - Portage - Configuration file
  become: true
  ansible.builtin.file:
    path: /etc/portage/make.conf
    owner: root
    group: portage
    mode: "0664"
