---
- name: Packages - Upgrade
  when:
    - system_packages_upgrade or (force_upgrade is defined and force_upgrade.changed)
    - packages_upgrade_policy is defined
  become: true
  ansible.builtin.package:
    name: "{{ packages_upgrade_policy.name | default(omit) }}"
    state: "{{ packages_upgrade_policy.state | default(omit) }}"
    upgrade: "{{ packages_upgrade_policy.upgrade | default(omit) }}"
  register: result
  until: result.failed == false
  retries: "{{ system_retries }}"
