---
- name: Distribution upgrade
  when: system_packages_upgrade
  block:
    - name: Packages - Upgrade - Portage
      become: true
      community.general.portage:
        deep: true
        newuse: true
        update: true
        package: '@world'
      register: result
      until: result.failed == false
      retries: "{{ system_retries }}"

    - name: Packages - Upgrade - Portage - Grub
      vars:
        has_changed: "{{ 'sys-boot/grub' in result.stdout }}"
      ansible.builtin.debug:
        msg: |-
          {{
            has_changed | ternary(
              "Grub has been changed",
              "Grub hasn't been changed"
            )
          }}
      changed_when: has_changed
      notify: grub-install

    - name: Packages - Upgrade - Portage - Service manager
      vars:
        has_changed: "{{ ('sys-apps/' + ansible_service_mgr) in result.stdout }}"
      ansible.builtin.debug:
        msg: |-
          {{
            has_changed | ternary(
              ansible_service_mgr + " has been changed",
              ansible_service_mgr + " hasn't been changed"
            )
          }}
      changed_when: has_changed
      notify: reboot

    - name: Packages - Upgrade - Portage - Glibc
      vars:
        has_changed: "{{ 'sys-libs/glibc' in result.stdout }}"
      ansible.builtin.debug:
        msg: |-
          {{
            has_changed | ternary(
              "Glibc has been changed",
              "Glibc hasn't been changed"
            )
          }}
      changed_when: has_changed
      notify: reload init system
