---
system_manage_hosts: true

system_hosts_domain: mydomain.tld
system_hosts_localhost_aliases:
  - me
  - myself
system_hosts_custom:
  - ip: '10.0.0.7'
    names:
      - host7
      - host7.domain.tld
