---
system_storages_partitions:
  - device: /dev/vdb
    flags:
      - lvm

system_storages_vg:
  - vg: datastore
    pvs: /dev/vdb1

system_storages_lvol:
  - vg: datastore
    lv: backups
    mount: /var/backups
    owner: vagrant
    mode: '0775'
