---
system_users_admin_group: administrators
system_users:
  - name: drno
    state: absent
  - name: jane
    comment: System administrator
    group: "{{ system_users_admin_group }}"
    groups:
      - "{{ system_sudo_group }}"
      - my_team
    shell: /bin/zsh
  - name: john
    group: users
  - name: my_service
    shell: /usr/bin/nologin
    system: true
    state: present
    uid: 207
system_users_groups:
  - name: my_company
  - name: villains
    state: absent
system_users_keys:
  - user: jane
    key: ssh-rsa AAAA test
