---
system_users_admin_group: administrators

system_users:
  - name: drno
    state: absent
    authorized_keys:
      - key: ssh-rsa BBBB test
  - name: vagrant   # Console login: vagrant / vagrant
    password: "$6$sc1Fu113nXXNx/KT$ZZ9QpiisBuXevhxIUdlN6tbAyxsR3BYUBayVP2NH0DPF6//sKe2bQ6vDGM0/wfAxRYZAd0tMQYVUtoEq.reB41"
  - name: jane
    comment: System administrator
    group: "{{ system_users_admin_group }}"
    groups:
      - "{{ system_sudo_group }}"
      - my_team
    authorized_keys:
      - key: ssh-rsa AAAA test
    shell: /bin/zsh
  - name: john
    group: users
  - name: my_service
    shell: /usr/bin/nologin
    system: true
    state: present
    uid: 207

system_users_groups:
  - name: my_company
  - name: villains
    state: absent
