---
- name: DNF - Distribution upgrade
  become: true
  ansible.builtin.dnf:
    allowerasing: true
    name: "*"
    state: latest
  register: result
  until: result.failed == false
  retries: "{{ system_retries }}"
