---
- name: Change default zone
  listen:
    - set default zone
  become: true
  ansible.builtin.command:
    cmd: firewall-cmd --set-default-zone {{ system_firewall_default_zone }}
  register: result
  changed_when: "'success' in result.stdout"

- name: Firewalld reload
  listen:
    - reload firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: restarted
