---
- name: Services
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/services.yml"

- name: Package managers
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/pkg_mgr.yml"

- name: Update CA certificates
  listen: update ca
  become: true
  ansible.builtin.command:
    cmd: "{{ default_ca.command }}"

- name: Grub make configuration
  listen: grub-mkconfig
  become: true
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg

- name: Restart network
  listen:
    - restart network service
  become: true
  ansible.builtin.service:
    name: "{{ default_networks.service_name }}"

- name: Skip network restart
  listen:
    - skip
  ansible.builtin.debug:
    msg: "You've to restart the network yourself !"

- name: Reboot
  listen:
    - grub-mkconfig
    - reboot
  become: true
  ansible.builtin.reboot:
    msg: Reboot initiated by gwerlas.system Ansible role
