---
- name: Service managers
  ansible.builtin.import_tasks: service_mgr.yml

- name: Package managers
  ansible.builtin.import_tasks: pkg_mgr.yml

- name: Update CA certificates
  listen: update ca
  become: true
  ansible.builtin.command:
    cmd: "{{ system_ca.command }}"

- name: Restart services impacted by changed hostname
  listen:
    - restart hostname
    - restart logind
  become: true
  ansible.builtin.service:
    name: "{{ (ansible_service_mgr == 'systemd') | ternary('systemd-logind', 'hostname') }}"
    state: restarted

- name: Grub make configuration
  listen: grub-mkconfig
  become: true
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg

- name: Restart network
  listen:
    - restart network service
  become: true
  ansible.builtin.service:
    name: "{{ system_networks_defaults.service_name }}"

- name: Skip network restart
  listen:
    - skip
  ansible.builtin.debug:
    msg: "You've to restart the network yourself !"

- name: Reboot
  listen:
    - grub-mkconfig
    - reboot
  become: true
  ansible.builtin.reboot:
    msg: Reboot initiated by gwerlas.system Ansible role
