---
- name: Auto merge /etc/conf.d/hostname
  listen: restart logind
  when: ansible_service_mgr == "openrc"
  become: true
  ansible.builtin.command:
    cmd: etc-update --automode -5 /etc/conf.d/hostname
  register: result
  changed_when: "'/etc/conf.d/hostname' in result.stdout"
