---
- name: Portage
  when: ansible_pkg_mgr == 'portage'
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/portage.yml"

- name: Packages - Cache update marker
  listen: update marker
  when: packages_update_policy.marker is defined
  become: true
  ansible.builtin.file:
    path: "{{ packages_update_policy.marker }}"
    state: touch
    modification_time: now
    mode: "0644"
