---
- name: Prevent circular dependencies and multilib compilation failures
  listen:
    - change profile
  become: true
  when: is_desktop
  environment:
    USE: minimal
  community.general.portage:
    oneshot: true
    getbinpkg: true
    newuse: true
    package:
      - sys-libs/glibc
      - sys-devel/gcc
      - dev-lang/rust{{ system_portage_use_bin_suffix | ternary('-bin', '') }}
      - dev-python/setuptools
      - media-libs/libsndfile

- name: Rebuild packages that need to be rebuilt
  listen:
    - change profile
    - emerge --newuse
  become: true
  community.general.portage:
    deep: true
    newuse: true
    update: "{{ system_packages_upgrade }}"
    package: '@world'

- name: Clean dependencies
  listen:
    - change profile
    - emerge --newuse
  become: true
  community.general.portage:
    depclean: true

- name: Genkernel
  when: system_portage_kernel is regex('\w+-sources')
  listen: genkernel
  become: true
  ansible.builtin.command:
    cmd: genkernel all
  changed_when: true

- name: Kernel modules rebuild
  listen:
    - genkernel
    - emerge @module-rebuild
  become: true
  community.general.portage:
    package: '@module-rebuild'
