---
- name: OpenRC
  when: ansible_service_mgr == "openrc"
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/openrc.yml"

- name: Systemd
  when: ansible_service_mgr == "systemd"
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/systemd.yml"

- name: Time service restart
  listen:
    - restart time service
  become: true
  ansible.builtin.service:
    name: "{{ service }}"
    state: restarted
  loop: "{{ time_backend.services }}"
  loop_control:
    loop_var: service
