---
- name: OpenRC
  when: ansible_service_mgr == "openrc"
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/openrc.yml"

- name: Systemd
  when: ansible_service_mgr == "systemd"
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/systemd.yml"

- name: Time service restart
  listen:
    - restart time service
  become: true
  ansible.builtin.service:
    name: "{{ services[time_backend_name] }}"
    state: restarted
