---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  provision: true
platforms:
  - name: archlinux
    box: archlinux/archlinux
    provider_raw_config_args: &raw_config
      - "cpu_mode = 'host-passthrough'"
      - "disk_bus = 'virtio'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"
    instance_raw_config_args:
      - 'vm.provision :shell, inline: "pacman -Syu --noconfirm git net-tools python3 sudo unzip which"'
  - name: debian12
    box: debian/testing64
    provider_raw_config_args: *raw_config
  - name: el8
    box: generic/centos8s
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: el9
    box: generic/centos9s
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: fedora36
    box: generic/fedora36
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: fedora37
    box: generic/fedora37
    memory: 2048
    provider_raw_config_args: *raw_config
  # Sandbox fail to compile, investigating later
  # - name: gentoo
  #   box: generic/gentoo
  #   cpus: 4
  #   memory: 8192
  #   provider_raw_config_args:
  #     - "cpu_mode = 'host-passthrough'"
  #     - "nic_model_type = 'virtio'"
  #     - "video_type = 'virtio'"
  #     - "disk_driver :cache => 'writeback'"
  #     - "storage :file, bus: 'virtio', cache: 'writeback'"
  - name: ubuntu2210
    box: generic/ubuntu2210
    memory: 2048
    provider_raw_config_args: *raw_config
lint: ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
