---
- name: Portage - Become root
  become: true
  block:
    - name: Portage - Distribution upgrade
      community.general.portage:
        deep: true
        newuse: true
        update: true
        package: '@world'
      register: result
      until: result.failed == false
      retries: "{{ system_retries }}"

    - name: Portage - Dependency cleaning
      community.general.portage:
        depclean: true
