---
- name: Networks - Prune - Unmanaged interfaces
  when: network_backend.template.dest is defined
  block:
    - name: Networks - Prune - Get existing interface configuration files
      ansible.builtin.find:
        paths:
          - "{{ network_backend.template.dest | dirname }}"
      register: result

    - name: Networks - Prune - Remove useless interfaces configuration files
      become: true
      ansible.builtin.file:
        state: absent
        path: "{{ system_networks_iface_configfile }}"
      vars:
        current_files: "{{ result.files | map(attribute='path') }}"
        ifaces: "{{ system_networks_interfaces | map(attribute='name') }}"
        regex: ^(.*)$
        replace: "{{ network_backend.template.dest | replace('%s', '\\1') }}"
      loop: |
        {{
          current_files |
          difference(
            ifaces |
            map('regex_replace', regex, replace)
          )
        }}
      loop_control:
        loop_var: system_networks_iface_configfile
      notify: "{{ system_networks_restart_handler }}"
