---
- name: Networks - Prune unmanaged interfaces
  when: default_networks.ifaces_confdir is defined
  block:
    - name: Networks - Prune - Get existing interface configuration files
      ansible.builtin.find:
        paths:
          - "{{ default_networks.ifaces_confdir }}"
      register: result

    - name: Networks - Prune - Debug
      ansible.builtin.debug:
        var: |
          {{
            result.files |
            map('basename') |
            difference(
              system_networks_interfaces |
              map(attribute='name') |
              sort |
              unique |
              lower
            )
          }}

    - name: Networks - Prune - Breakpoint
      ansible.builtin.fail:

    - name: Networks - Prune - Remove useless interfaces configuration files
      become: true
      ansible.builtin.file:
        state: absent
        path: "{{ system_networks_iface_configfile }}"
      loop: |
        {{
          result.files |
          map('basename') |
          difference(
            system_networks_interfaces |
            map(attribute='name') |
            sort |
            unique |
            lower
          )
        }}
      loop_control:
        loop_var: system_networks_iface_configfile
      notify: "{{ system_networks_restart_handler }}"
