---
- name: Networks - Interfaces configuration from template
  become: true
  block:
    - name: Networks - Interfaces configuration - Directory
      ansible.builtin.file:
        state: directory
        path: "{{ network_backend.template.dest | dirname }}"
        mode: "0755"

    - name: Networks - Interfaces configuration - Files
      when: |
        (not netiface.name in ansible_interfaces)
        or
        (system_networks_check_mode == 'files')
      ansible.builtin.template:
        src: "{{ network_backend.template.src }}"
        dest: "{{ network_backend.template.dest | format(netiface.name) }}"
        mode: "0644"
      loop: "{{ system_networks_interfaces }}"
      loop_control:
        loop_var: netiface
      notify: "{{ system_networks_restart_handler }}"
      register: result
      until: result is succeeded
