---
- name: Packages - Requirements - Portage - Kernel - Symlink - List kernels
  ansible.builtin.find:
    path: /usr/src
    pattern: linux-*
    file_type: directory
  register: result

- name: Packages - Requirements - Portage - Kernel - Symlink
  become: true
  when: result.matched > 0
  vars:
    latest: |-
      {{
        result.files |
        map(attribute='path') |
        community.general.version_sort |
        last
      }}
  ansible.builtin.file:
    src: "{{ latest }}"
    dest: /usr/src/linux
    state: link
    follow: false
    force: true
  notify:
    - genkernel
    - emerge @module-rebuild
