---
- name: Portage - Preparations before emere --sync
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/package-managers/portage/{{ portage_task }}.yml"
  loop:
    - permissions
    - cache
    - profile
    - equery
    - use-flags
  loop_control:
    loop_var: portage_task
