---
- name: System binaries
  when: "'container' not in ansible_virtualization_tech_guest"
  block:
    - name: Portage profile
      ansible.builtin.import_tasks: portage-profile.yml

    - name: Kernel related packages settings
      ansible.builtin.copy:
        src: "{{ system_portage_kernel_file }}"
        dest: "/etc/portage/{{ system_portage_kernel_file }}"
        owner: "{{ ansible_user_id }}"
        group: portage
        mode: 0664
      loop:
        - package.license/kernel
        - package.use/kernel
      loop_control:
        loop_var: system_portage_kernel_file
      notify: emerge --newuse

    - name: Kernel package and its dependencies
      become: true
      community.general.portage:
        update: "{{ system_package_update }}"
        package:
          - sys-kernel/linux-firmware
          - virtual/dist-kernel
      register: system_emerge_kernel
      notify:
        - grub-mkconfig

    - name: Get available kernels
      ansible.builtin.find:
        path: /boot
        pattern: vmlinuz-*
      register: system_available_kernels

    - name: Kernel symlink for external modules
      become: true
      when: system_available_kernels.matched > 0
      ansible.builtin.file:
        src: /usr/src/linux-{{ (system_available_kernels.files | map(attribute='path') | map('regex_search', 'vmlinuz-(.*)', '\1') | last).0 }}
        dest: /usr/src/linux
        state: link
      notify:
        - emerge @module-rebuild

- name: System update
  when: system_package_update
  become: true
  community.general.portage:
    deep: true
    newuse: true
    update: true
    package: '@world'
