---
- name: Portage profile
  become: true
  ansible.builtin.file:
    src: "{{
      '../..' + system_portage_directory + '/profiles/' +
      system_portage_profile[system_profile] +
      ('/systemd' if ansible_service_mgr == 'systemd' else '') }}"
    dest: /etc/portage/make.profile
    state: link
  notify: emerge --newuse
