---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  provision: true
platforms:
  - name: archlinux
    box: archlinux/archlinux
    provider_raw_config_args: &raw_config
      - "cpu_mode = 'host-passthrough'"
      - "disk_bus = 'virtio'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"
    instance_raw_config_args:
      - 'vm.provision :shell, inline: "pacman -Sy --noconfirm git net-tools python3 sudo unzip which"'
  - name: debian-testing
    box: debian/testing64
    provider_raw_config_args: *raw_config
  - name: centos9s
    box: generic/centos9s
    memory: 2048
    provider_raw_config_args: *raw_config
    instance_raw_config_args:
      - 'vm.provision :shell, inline: "rm /etc/yum.repos.d/*.repo"'
  - name: gentoo
    box: generic-x64/gentoo
    cpus: 4
    memory: 8192
    provider_raw_config_args:
      - "cpu_mode = 'host-passthrough'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"
lint: ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
