---
- name: Verify role for Stream distributions
  hosts: all
  tasks:
    - name: Rsync
      ansible.posix.synchronize:
        src: verify.yml
        dest: /tmp/verify.yml

    - name: Time synchronisation
      when: ansible_service_mgr == 'systemd'
      ansible.builtin.command:
        cmd: timedatectl
      register: result
      failed_when: |
        (result.rc > 0) or
        ('synchronized: yes' not in result.stdout) or
        ('service: active' not in result.stdout)
      changed_when: false

    - name: Time synchronisation
      when: ansible_service_mgr == 'openrc'
      ansible.builtin.command:
        cmd: chronyc sourcestats
      changed_when: false
