---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: archlinux
    image: gwerlas/ansible-guest-archlinux
    volumes: &volumes
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian10
    image: gwerlas/ansible-guest-debian:buster
    volumes: *volumes
  - name: debian11
    image: gwerlas/ansible-guest-debian:bullseye
    volumes: *volumes
  - name: debian12
    image: gwerlas/ansible-guest-debian:bookworm
    volumes: *volumes
  - name: el7
    image: gwerlas/ansible-guest-centos:7
    volumes: *volumes
  - name: el8
    image: gwerlas/ansible-guest-almalinux:8
    volumes: *volumes
  - name: el9
    image: gwerlas/ansible-guest-almalinux:9
    volumes: *volumes
lint: ansible-lint
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible
verifier:
  name: ansible
