---
- name: APT - Configuration files
  become: true
  block:
    - name: Prevent APT lock acquired by the daily upgrade
      become: true
      ansible.builtin.systemd:
        name: apt-daily-upgrade
        state: stopped

    - name: APT - Sources list
      ansible.builtin.template:
        src: apt/sources.list.j2
        dest: /etc/apt/sources.list
        mode: "0644"
