---
- name: Packages - Prepare - APT - Configuration files
  become: true
  block:
    - name: Packages - Prepare - APT - Prevent lock file acquired by the daily upgrade
      become: true
      ansible.builtin.systemd:
        name: apt-daily-upgrade
        state: stopped

    - name: Packages - Prepare - APT - Sources list
      ansible.builtin.template:
        src: apt/sources.list.j2
        dest: /etc/apt/sources.list
        mode: "0644"

    - name: Packages - Prepare - APT - Use backports
      when: debian_release == "buster"
      ansible.builtin.template:
        src: apt/preferences.d/50backports.j2
        dest: /etc/apt/preferences.d/50backports
        mode: "0644"
      register: force_upgrade
