---
- name: Become root
  become: true
  block:
    - name: Pacman - Install
      community.general.pacman:
        name: "{{ system_packages }}"
      register: result
      until: result.failed == false
      retries: "{{ system_retries }}"
  rescue:
    - name: Pacman - Install rescue
      ansible.builtin.command:
        cmd: pacman -Syu --noconfirm {{ system_packages | join(' ') }}
      register: result
      until: result.failed == false
      retries: "{{ system_retries }}"
      changed_when: not 'there is nothing to do' in result.stdout
