---
- name: Packages - Install - Show the list
  ansible.builtin.debug:
    var: system_packages
    verbosity: 1

- name: Packages - Install
  become: true
  ansible.builtin.package:
    name: "{{ system_packages }}"
  register: result
  until: result.failed == false
  retries: "{{ system_retries }}"
