---
- name: Packages - Prewash
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/packages/prewash/{{ pre_task }}.yml"
  loop:
    - services
    - packages
  loop_control:
    loop_var: pre_task

- name: Packages - Prewash - Package managers
  ansible.builtin.include_tasks:
    file: "{{ pre_task }}"
  with_first_found:
    - files:
        - "{{ ansible_pkg_mgr }}.yml"
      paths:
        - "{{ role_path }}/tasks/packages/prewash"
      skip: true
  loop_control:
    loop_var: pre_task
