---
- name: Packages - Requirements
  ansible.builtin.include_tasks:
    file: "{{ req_task }}"
  with_first_found:
    - files:
        - "{{ ansible_pkg_mgr }}.yml"
      paths:
        - "{{ role_path }}/tasks/packages/requirements"
      skip: true
  loop_control:
    loop_var: req_task

- name: Packages - Requirements - Modules load directory
  ansible.builtin.file:
    path: /etc/modules-load.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Packages - Requirements - Flush handlers
  ansible.builtin.meta: flush_handlers
