---
- name: Packages - Cache update detection script
  become: true
  ansible.builtin.template:
    src: needs-update.j2
    dest: "{{ system_bin_path }}/needs-update"
    mode: "0755"

- name: Packages - Cache update detection
  ansible.builtin.command:
    cmd: needs-update
  register: result
  failed_when: result.rc > 1
  changed_when: result.rc == 1
  notify: cache update

- name: Packages - Cache update
  ansible.builtin.meta: flush_handlers
