---
- name: Packages - Update
  ansible.builtin.include_tasks:
    file: "{{ upd_task }}"
  with_first_found:
    - files:
        - "{{ ansible_pkg_mgr }}.yml"
        - other.yml
      paths:
        - "{{ role_path }}/tasks/packages/update"
  loop_control:
    loop_var: upd_task
