---
- name: Packages - Cleanup - Portage
  become: true
  community.general.portage:
    depclean: true
  notify: emerge --newuse

- name: Search and remove unused kernels
  vars:
    current_version: |-
      {{
        ansible_kernel |
        regex_replace('(.*)-' + ansible_userspace_architecture, '\1')
      }}
  block:
    - name: Packages - Cleanup - Portage - Unused kernels - Sources
      ansible.builtin.find:
        path: /usr/src
        pattern: linux-*
        file_type: directory
        excludes:
          - "*{{ current_version }}*"
      register: kernel_sources

    - name: Search and remove files and directories
      vars:
        sources: |
          {{
            kernel_sources.files |
            map(attribute='path') |
            map('basename') |
            map('regex_replace', 'linux-(.*)', '\1')
          }}
        latest: |-
          {{
            sources |
            community.general.version_sort |
            last
          }}
        obsoletes: |
          {{
            sources |
            reject('in', [current_version, latest])
          }}
      when: obsoletes | length > 0
      become: true
      block:
        - name: Packages - Cleanup - Portage - Unused kernels - Remove
          vars:
            patterns:
              - initramfs-%s-{{ ansible_userspace_architecture }}.img
              - initramfs-%s-{{ ansible_userspace_architecture }}.img.old
              - System.map-%s-{{ ansible_userspace_architecture }}
              - System.map-%s-{{ ansible_userspace_architecture }}.old
              - vmlinuz-%s-{{ ansible_userspace_architecture }}
              - vmlinuz-%s-{{ ansible_userspace_architecture }}.old
          ansible.builtin.file:
            path: /boot/{{ kernel_version.1 | regex_replace('%s', kernel_version.0) }}
            state: absent
          with_nested:
            - "{{ obsoletes }}"
            - "{{ patterns }}"
          loop_control:
            loop_var: kernel_version
          notify: grub-mkconfig

        - name: Packages - Cleanup - Portage - Unused kernels - Remove modules
          ansible.builtin.file:
            path: /lib/modules/{{ kernel_version }}-{{ ansible_userspace_architecture }}
            state: absent
          loop: "{{ obsoletes }}"
          loop_control:
            loop_var: kernel_version

        - name: Packages - Cleanup - Portage - Unused kernels - Remove sources
          ansible.builtin.file:
            path: /usr/src/linux-{{ kernel_version }}
            state: absent
          loop: "{{ obsoletes }}"
          loop_control:
            loop_var: kernel_version
