---
- name: Packages - Prewash - Packages - System packages facts
  ansible.builtin.package_facts:

- name: Packages - Prewash - Packages - Variables
  vars:
    packages_keys: |
      {{
        supported_time_backends |
        dict2items |
        rejectattr('key', '==', time_backend_name) |
        map(attribute='key') |
        difference(masks.packages | default([]))
      }}
    packages: |
      {{
        (family_packages | default({})) |
        combine(distro_packages | default({}))
      }}
  ansible.builtin.set_fact:
    to_remove: |
      {{
        (
          (packages_keys | intersect(packages.keys()) | map('extract', packages))
        + (packages_keys | difference(packages.keys()))
        ) | flatten | unique | intersect(ansible_facts.packages.keys())
      }}

- name: Packages - Prewash - Packages - Remove
  when: to_remove | length > 0
  become: true
  ansible.builtin.package:
    name: "{{ to_remove }}"
    state: absent
