---
- name: Packages - Prewash - Services
  when: not in_container
  block:
    - name: Packages - Prewash - Services - Facts
      ansible.builtin.service_facts:

    - name: Packages - Prewash - Services - Disable
      become: true
      ansible.builtin.service:
        name: "{{ service }}"
        state: stopped
        enabled: false
      vars:
        current_services: |
          {{
            ansible_facts.services |
            dict2items |
            json_query("[?value.status!='not-found'].key")
          }}
        services_keys: |
          {{
            supported_time_backends |
            dict2items |
            rejectattr('key', '==', time_backend_name) |
            map(attribute='value') |
            map(attribute='services') |
            flatten
          }}
      loop: |
        {{
          ( (services_keys | intersect(system_services_dict.keys()) | map('extract', system_services_dict))
          + (services_keys | difference(system_services_dict.keys()))
          ) | map('intersect', current_services) | flatten
        }}
      loop_control:
        loop_var: service
