---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian11
    image: gwerlas/ansible-guest-debian:bullseye
    pre_build_mage: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
