---
- name: Portage - Load initial config
  ansible.builtin.slurp:
    src: /etc/portage/make.conf
  register: result

- name: Portage - Set facts
  vars:
    initial_config: "{{ result.content | b64decode }}"
    portdir_matches: |-
      {{
        initial_config |
        regex_findall('(?<!#)PORTDIR=\"(.+)\"')
      }}
  ansible.builtin.set_fact:
    initial_portdir: "{{ (portdir_matches | length > 0) | ternary(portdir_matches | last, '') }}"

- name: Portage - Tasks sequence
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/package-managers/portage/{{ portage_task }}.yml"
  loop:
    - permissions
    - portdir
    - profile
    - repos
    - equery
    - make.conf
    - profile/upgrade
  loop_control:
    loop_var: portage_task

- name: Portage - Configure - Ensure git is installed
  become: true
  community.general.portage:
    package: dev-vcs/git
