---
- name: Portage - Permissions - Deployer admin in portage group
  when: ansible_user_id != 'root'
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
      - portage

- name: Portage - Permissions - Reset SSH connection
  ansible.builtin.meta: reset_connection

- name: Portage - Permissions - Configuration directories
  become: true
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    group: portage
    mode: "0775"
  loop:
    - /etc/portage/
    - /etc/portage/binrepos.conf
    - /etc/portage/package.accept_keywords
    - /etc/portage/package.license
    - /etc/portage/package.mask
    - /etc/portage/package.use
    - /etc/portage/repos.conf
    - /etc/portage/savedconfig
    - /var/cache/distfiles
    - "{{ system_portage_repos_directory }}"
  loop_control:
    loop_var: dir
