---
- name: Portage - Check for profiles
  ansible.builtin.stat:
    path: "{{ system_portage_directory + '/profiles' }}"
  register: profiles

- name: Portage - Profile - Manual emerge sync
  when: not profiles.stat.exists
  become: true
  ansible.builtin.command:
    cmd: emerge --sync
  register: result
  changed_when: result.stdout | regex_search('Number of files. (\\d+)', '\\1') | first | int > 1

- name: Portage - Profile - Symbolic link
  become: true
  ansible.builtin.file:
    src: |-
      {{
        '../..' + system_portage_directory + '/profiles/' +
        system_portage_profile[system_profile] +
        ('/systemd' if ansible_service_mgr == 'systemd' else '')
      }}
    dest: /etc/portage/make.profile
    state: link
    force: true
  notify: emerge --newuse
