---
- name: Portage - Profile - Check for profiles directory
  ansible.builtin.stat:
    path: "{{ system_portage_directory }}/profiles"
  register: dir

- name: Portage - Profile - Manual emerge sync
  when: not dir.stat.exists
  become: true
  ansible.builtin.command:
    cmd: emerge --sync
  register: sync
  changed_when: sync.stdout | regex_search('Number of files. (\\d+)', '\\1') | first | int > 1

- name: Portage - Profile - Check for broken link
  ansible.builtin.stat:
    path: /etc/portage/make.profile
    follow: true
  register: link

- name: Portage - Profile - Force to default profile
  when: not link.stat.exists
  become: true
  ansible.builtin.file:
    src: |-
      {{
        '../..' + system_portage_directory +
        '/profiles/default/linux/amd64/17.1/no-multilib' +
        ('/systemd/merged-usr' if ansible_service_mgr == 'systemd' else '')
      }}
    dest: /etc/portage/make.profile
    state: link
    force: true
    follow: false
  notify:
    - emerge --newuse
