---
- name: Portage - Profile - Tasks sequence
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/package-managers/portage/profile/{{ portage_profile_task }}.yml"
  loop:
    - sync
    - facts
    - link
  loop_control:
    loop_var: portage_profile_task
