---
- name: Portage - Needs update
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/package-managers/needs-update.yml"

- name: Portage - Cache update
  when: system_cache_needs_update
  become: true
  community.general.portage:
    sync: "{{ 'web' if system_manage_proxies else true }}"
  register: result
  until: result.failed == false
  retries: "{{ system_retries }}"
