---
- name: Verify role with Systemd Timesyncd
  hosts: all
  tasks:
    - name: Synchronisation
      when: ansible_service_mgr == 'systemd'
      ansible.builtin.command:
        cmd: timedatectl
      register: result
      failed_when: |
        (result.rc > 0) or
        ('synchronized: yes' not in result.stdout)
      changed_when: false

    - name: Service
      ansible.builtin.command:
        cmd: chronyc sourcestats
      register: result
      changed_when: false
